# Image Catalog — PMJAY_MH_S_G_R1_2026032910015645

**Package:** MC011A  ·  **Model:** accounts/ajeya-rao-k-eckusf6m/deployments/euufjyfd  ·  **Images:** 21

## Overview

| # | Source | Page | Type | Body region | Stage | Quality |
|---|--------|------|------|-------------|-------|---------|
| 0 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 1/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 1 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 2/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 2 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 3/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 3 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 4/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 4 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 5/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 5 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 6/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 6 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 7/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 7 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 8/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 8 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 9/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 9 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 10/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 10 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 11/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 11 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 12/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 12 | 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf | 13/13 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 13 | 000256__PMJAY_MH_S_G_R1_2026032910015645__PTCA_REPORT.pdf | 1/3 | Typed report | Coronary arteries | post-procedure | good |
| 14 | 000256__PMJAY_MH_S_G_R1_2026032910015645__PTCA_REPORT.pdf | 2/3 | Typed report | Coronary tree — left system, Right coronary artery | post-procedure | good |
| 15 | 000256__PMJAY_MH_S_G_R1_2026032910015645__PTCA_REPORT.pdf | 3/3 | Coronary Angiogram | Coronary tree — left system | post-procedure | good |
| 16 | 000264__PMJAY_MH_S_G_R1_2026032910015645__CAG_REPORT.pdf | 1/2 | Typed report | Coronary tree | post-procedure | good |
| 17 | 000264__PMJAY_MH_S_G_R1_2026032910015645__CAG_REPORT.pdf | 2/2 | Coronary Angiogram | Coronary tree — left system | post-procedure | good |
| 18 | 000274__PMJAY_MH_S_G_R1_2026032910015645__CAG_IMAGES.pdf | 1/3 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 19 | 000274__PMJAY_MH_S_G_R1_2026032910015645__CAG_IMAGES.pdf | 2/3 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 20 | 000274__PMJAY_MH_S_G_R1_2026032910015645__CAG_IMAGES.pdf | 3/3 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |

## [0] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 1/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 1° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible in coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within the coronary artery. The view is RAO 1° / CRAN 3°, and the patient is a 73-year-old female. Image acquisition details and system parameters are visible on the screen.

**Key observations:**
- Guidewire is visible within the coronary artery
- Patient identifier: 73/F
- Acquisition date: 3/31/2028
- View angle: RAO 1° / CRAN 3°
- System: AXIOM-Artis
- Image parameters: EE 11%, DDO 45%, WC 1905, WW 2600

**Dates found:** 31/03/2028

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2414/03/2026
73/F
* 3/31/1953
3/31/2028
1:18:09 PM
1 - 33/194
FL Angio
om 20
A
D 40
RAO 1° / CRAN 3°
AXIOM-Artis
VD 12A 241911
HFS
/com////
EE 11%
DDO 45%
WC 1905
WW 2600
```

</details>

---

## [1] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 2/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 1° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible within coronary vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within the coronary vasculature, captured during an interventional procedure. The view is a left anterior oblique (LAO) projection with cranial tilt.

**Key observations:**
- Guidewire is visible within a coronary artery
- Patient age: 73 years
- Projection: RAO 1° / CRAN 3°
- Image acquisition date: 3/31/2026
- Image acquisition time: 1:18:49 PM
- Image type: FL Angio (fluoroscopic angiogram)

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2414/03/2026
* 3/31/1953
3/31/2026
1:18:49 PM
2-13/63
73/F
AXIOM-Artis
V0172 24 (011)
HFS
/scan///
FL Angio
cm 20
A
D 40
RAO 1° / CRAN 3°
EE 11%
DDO 45%
WC 1905
WW 2000
```

</details>

---

## [2] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 3/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 1° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire and catheter visible within coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system. A guidewire and catheter are visible within the vessel lumen. The image is acquired in a RAO 1° / CRAN 3° projection.

**Key observations:**
- Coronary angiogram of the left system
- Guidewire and catheter present within vessel
- Projection: RAO 1° / CRAN 3°
- Image acquired on 3/31/2026 at 1:19:46 PM
- Patient age: 73/F (redacted)
- Image parameters: EE 28%, DDO 59%, WC 2050, WW 2300

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2414/03/2026
* 3/31/1953
3/31/2026
1:19:46 PM
4 - 16/30
0.97 sec
Coro 2020
cm 20
A
D 168
RAO 1° / CRAN 3°
AXIOM-Artis
V012A 241011
HFS
/oom/III
CARD 15 65
EE 28%
DDG 59%
WC 2050
WW 2300
```

</details>

---

## [3] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 4/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 2° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire and catheter visible within coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with a guidewire and catheter in place. The image is captured from a LAO 2° / CRAN 3° projection during a procedure on a 73-year-old female patient.

**Key observations:**
- Guidewire and catheter are visible within the coronary artery
- Patient is 73 years old (73F)
- Projection is LAO 2° / CRAN 3°
- Image acquired on 3/31/2026 at 1:28:45 PM
- Image is from the AXIOM-Artis system

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2414/US/2026
* 3/31/1953
3/31/2026
1:28:45 PM
10 - 17731
1.04 sec
73F
AXIOM-Artis
VP12A 241011
HES
/csm/III
Coro 2020
cm 20
A
D 169
LAO 2° / CRAN 3°
EE 26%
DDO 59%
WC 2050
WW 2300
```

</details>

---

## [4] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 5/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 2° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible within coronary vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within the coronary artery, captured during an interventional procedure. The image displays cath-lab monitor UI elements including patient demographics, acquisition parameters, and view angles.

**Key observations:**
- Guidewire is visible within a coronary vessel
- Image acquired in LAO 2° / CRAN 3° projection
- Patient age: 73 years, female
- Procedure time: 3/31/2028, 1:27:10 PM
- Image acquisition parameters: CARD 15%, EE 27%, DDO 50%, WC 2050, WW 2390

**Dates found:** 31/03/2028

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24/14/03/2028
73/F
* 3/31/1953
3/31/2028
1:27:10 PM
11 - 10/29
0.58 sec
Coro 2020
cm 20
A
D 169
LAO 2° / CRAN 3°
AXIOM-Aris
VD12A 241011
FES
/son////
CARD 15%
EE 27%
DDO 50%
WC 2050
WW 2390
```

</details>

---

## [5] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 6/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 2° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire and stent visible in left coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery with a guidewire and stent deployed. The view is LAO 2° / CRAN 3°, and patient data indicates a 73-year-old female. Image acquisition parameters and post-processing settings are visible on the monitor interface.

**Key observations:**
- Left coronary artery with guidewire and stent visible
- View angle: LAO 2° / CRAN 3°
- Patient age: 73 years, female
- Image acquisition time: 1:30 PM on 3/31/2026
- Post-processing settings: EE 28%, DOO 50%, WC 2050, WW 2300

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2414/03/2026
73/F
3/31/2026
1:30 14 PM
17 - 31/63
1.04 sec
Coro 2020
cm 18
A
D 167
LAO 2° / CRAN 3°
EE 28%
DOO 50%
WC 2050
WW 2300
```

</details>

---

## [6] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 7/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 41° / CRAN 3°  ·  **Stage:** intra-procedure (Fluoroscopic image with angiographic overlay, patient identifier '73/F', and cath-lab UI elements)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing a left coronary angiogram in LAO 41° / CRAN 3° view. The image displays vessel structures with UI overlays indicating patient ID '73/F', acquisition time, and image processing parameters.

**Key observations:**
- Fluoroscopic image of the coronary vasculature
- View angle: LAO 41° / CRAN 3°
- Patient identifier: 73/F
- Image acquisition time: 3/3/172026 1:35:49 PM
- Image processing parameters: EE 12%, DDO 45%, WC 1905, WW 2800
- Equipment: AXIOM-Artis VD12A 241011

**Dates found:** 03/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
241#103#2026
*3/3/172026
1:35:49 PM
20 - 53/123
73/F
AXIOM-Artis
VD12A 241011
HFS
/com/\\\\
Store Fluoro
View
Image
PostProc
Adjust
FL Angio
cm 20
A
D 40
LAO 41° / CRAN 3°
EE 12%
DDO 45%
WC 1905
WW 2800
```

</details>

---

## [7] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 8/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 41° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible within coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with a guidewire in place. The image is captured on a Siemens AXIOM-Artis system with specific acquisition parameters and projection angles.

**Key observations:**
- Guidewire is visible within the coronary artery lumen
- Projection angle is LAO 41° / CRAN 3°
- Image acquisition date is 3/31/2020
- System is AXIOM-Artis, model VD12A 241011
- Image parameters: EE 29%, DDO 50%, WC 2050, WW 2300

**Dates found:** 31/03/2020

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
3/31/2020
1:36:46 PM
22-38/57
1.21 sec
AXIOM-Artis
VD12A 241011
HFS
/com////
EE 29%
DDO 50%
WC 2050
WW 2300
Coro 2020
cm 20
A
D 172
LAO 41° / CRAN 3°
```

</details>

---

## [8] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 9/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 41° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible within coronary vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within the coronary vasculature. The image is captured from a left anterior oblique (LAO) and cranial (CRAN) projection, with overlayed system parameters indicating the patient's age, time, and imaging settings.

**Key observations:**
- Guidewire is visible within the coronary artery
- Image acquired in LAO 41° / CRAN 3° projection
- System parameters show EE 28%, DDO 50%, WC 2050, WW 2300
- Patient identifier: 73/F

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
73/F
* 3/31/2026
1:36:48 PM
24-29/50
0.67 sec
AXIOM-Artis
VD12A 241011
HFS
/com////
CARD 30 fps
View Image DSA
EE 28%
DDO 50%
WC 2050
WW 2300
Coro 2020
cm 20
A
D 170
LAO 41° / CRAN 3°
```

</details>

---

## [9] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 10/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 41° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible within coronary vessel)  ·  **Quality:** good — Partial view of the coronary tree, Digital overlay obscures some anatomical detail, Patient identifiers redacted

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within the left coronary artery system, captured during a procedure. The image displays cath-lab UI overlays including acquisition parameters and patient positioning.

**Key observations:**
- A guidewire is visible traversing the left coronary artery system.
- Image acquired at LAO 41° / CRAN 3° projection.
- Procedure timestamp: 3/31/2025, 1:30:08 PM.
- Image parameters: CARD 30 ms, EE 26%, DDO 50%, WC 2050, WW 2300.

**Dates found:** 31/03/2025

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24/11/03/2025
* 3/31/1983
3/31/2025
1:30:08 PM
25 - 42/184
1.38 sec
Coro 2020
cm 20
A 187
LAO 41° / CRAN 3°
AXIOM-Artis
VD12A 241011
HFS
/comill/
CARD 30 ms
EE 26%
DDO 50%
WC 2050
WW 2300
```

</details>

---

## [10] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 11/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 41° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible in coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire in the left coronary artery system, captured during a procedure on March 31, 2026. The image displays cath-lab UI overlays including patient orientation (LAO 41° / CRAN 3°) and image acquisition parameters.

**Key observations:**
- Guidewire visible within the coronary artery
- Image captured during an interventional procedure
- Patient orientation: LAO 41° / CRAN 3°
- Date and time stamp: 3/31/2026 1:42:08 PM
- Image acquisition parameters visible (EE 27%, DDO 50%, WC 1925, WW 2300)

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
3/31/2026 1:42:08 PM 20 - 23/45 1.12 sec AXIOM-Artis VD12A 2H1011 HF3 /corvill/ CARD 30 s EE 27% DDO 50% WC 1925 WW 2300 Cord 2020 cm 20 A D 189 LAO 41° / CRAN 3°
```

</details>

---

## [11] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 12/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 41° / CRAN 3°  ·  **Stage:** intra-procedure (Guidewire visible in vessel lumen)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within a coronary vessel, captured during an interventional procedure. The image is displayed on a cath-lab monitor with acquisition parameters and patient details visible.

**Key observations:**
- Guidewire is visible within the vessel lumen
- Image acquired in LAO 41° / CRAN 3° projection
- Patient age: 73 years, female
- Procedure type: FL Angio (fluoroscopic angiography)
- Image parameters: EE 11%, DDO 45%, WC 1905, WW 2600

**Dates found:** 03/31/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24/14/03/2026
73/F
H
3/31/2026
1:43:37 PM
32 - 4/58
AXIOM-Artis
VD12A 241011
HFS
/com////
FL Angio
cm 20
A
D 40
LAO 41° / CRAN 3°
EE 11%
DDO 45%
WC 1905
WW 2600
```

</details>

---

## [12] 000255__PMJAY_MH_S_G_R1_2026032910015645__PTCA_IMAGES.pdf — page 13/13

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 40° / CAUD 21°  ·  **Stage:** intra-procedure (Angiographic view of coronary artery with contrast opacification and visible guidewire)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with contrast opacification. The view is acquired in LAO 40° / CAUD 21° projection. A guidewire is visible within the vessel lumen. The image is from a cath-lab monitor with overlayed acquisition parameters.

**Key observations:**
- Coronary artery tree visualized with contrast medium
- Guidewire present within vessel lumen
- Projection: LAO 40° / CAUD 21°
- Patient age: 73 years
- Acquisition time: 11:44:05 PM on 3/5/2025
- Image parameters: CARD 30 Hz, EE 28%, DDO 50%, WC 1877, WW 2300

**Dates found:** 05/03/2025

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
241Mudaraj26
73/F
3/5/12025
11:44:05PM
35 - 156.2
1:17 sec
Coro 2020
cm 16
A
D 171
LAO 40° / CAUD 21°
VD12A241011
HFS
/com////
CARD 30 Hz
EE 28%
DDO 50%
WC 1877
WW 2300
```

</details>

---

## [13] 000256__PMJAY_MH_S_G_R1_2026032910015645__PTCA_REPORT.pdf — page 1/3

**Type:** Typed report  ·  **Body region:** Coronary arteries  ·  **Stage:** post-procedure (Final result section with TIMI III Flow and Residual stenosis 0%)  ·  **Quality:** good

**Summary.** This is a typed PTCA (Percutaneous Transluminal Coronary Angioplasty) report detailing the procedure performed on a 73-year-old female patient on March 31, 2026. The report describes interventions on both the left circumflex (LCX) and right coronary artery (RCA) using stents and balloons, concluding with an excellent result, TIMI III flow, and 0% residual stenosis.

**Key observations:**
- Procedure performed on March 31, 2026, on a 73-year-old female.
- PTCA performed on LCX and RCA arteries.
- Stents deployed: LAD-GRACE 3.0 X 16 mm and RCA-GRACE 2.75 X 32 mm.
- Final result: Excellent, with TIMI III flow and 0% residual stenosis.
- Patient was given 10,000 IU of heparin during the procedure.

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
NAME : DATE : 31/03/2026
AGE : 73 YRS. SEX : FEMALE
CATH ID : 2414/03/2026 IP NO : AHH-1798/03/26
CORONARY ANGIOPLASTY REPORT ( PTCA )
Route : LEFT FEMORAL ARTERY
Procedure : PTCA TO LCX
Access : 7F SHEATH
RFA : 130/80 mmhg
Heparin : 10,000 IU.
Guiding Catheter : 7F EBU 3.0
Coronary wire : Fielder FC Wire
Pre-dilatation : Sapphire 2.0 X 10 mm balloon at 16 atm.
Stent : LAD- GRACE 3.0 X 16 mm at 12 atm.[DES]
Post- dilatation : Sapphire nc 3.25 x 12 mm balloon at 19 atm.
Procedure : PTCA TO RCA
Access : 7F SHEATH
RFA/RRA : 130/80 mmhg
Guiding Catheter : 6F JR 3.0
Inj Heparin : 10000 IU
Coronary wire : Sion Blue
Pre-dilatation : Sapphire 2.0 X 10 mm balloon at 16 atm.
Stent : RCA- GRACE 2.75 X 32 mm at 11 atm.[DES]
Post- dilatation : Sapphire nc 3.0 x 10 mm balloon at 19 atm.
POST PTCA ACT : 290
Final result : Excellent final result , no haze / dissection / thrombus
TIMI III Flow
Residual stenosis 0%

सुचना * पुडील केलेस येताना हा कामद सोबत आणावा. * औषधी अंतर्ज्ञान असल्यास प्रथम सांगणे. * औषधे डॉक्टरांना दाखवूच घ्या.
```

</details>

**English:**

```
NAME : DATE : 31/03/2026
AGE : 73 YRS. SEX : FEMALE
CATH ID : 2414/03/2026 IP NO : AHH-1798/03/26
CORONARY ANGIOPLASTY REPORT ( PTCA )
Route : LEFT FEMORAL ARTERY
Procedure : PTCA TO LCX
Access : 7F SHEATH
RFA : 130/80 mmhg
Heparin : 10,000 IU.
Guiding Catheter : 7F EBU 3.0
Coronary wire : Fielder FC Wire
Pre-dilatation : Sapphire 2.0 X 10 mm balloon at 16 atm.
Stent : LAD- GRACE 3.0 X 16 mm at 12 atm.[DES]
Post- dilatation : Sapphire nc 3.25 x 12 mm balloon at 19 atm.
Procedure : PTCA TO RCA
Access : 7F SHEATH
RFA/RRA : 130/80 mmhg
Guiding Catheter : 6F JR 3.0
Inj Heparin : 10000 IU
Coronary wire : Sion Blue
Pre-dilatation : Sapphire 2.0 X 10 mm balloon at 16 atm.
Stent : RCA- GRACE 2.75 X 32 mm at 11 atm.[DES]
Post- dilatation : Sapphire nc 3.0 x 10 mm balloon at 19 atm.
POST PTCA ACT : 290
Final result : Excellent final result , no haze / dissection / thrombus
TIMI III Flow
Residual stenosis 0%

Note: * Please bring the patient's medical records with you. * Inform the doctor if you have any allergies. * Show all medicines to the doctor.
```

---

## [14] 000256__PMJAY_MH_S_G_R1_2026032910015645__PTCA_REPORT.pdf — page 2/3

**Type:** Typed report  ·  **Body region:** Coronary tree — left system, Right coronary artery  ·  **Stage:** post-procedure (PTCA TO LCX & RCA WITH 2 STENT DONE)  ·  **Quality:** good

**Summary.** This is a typed procedural report detailing a percutaneous coronary intervention (PTCA) performed on the left circumflex artery (LCX) and right coronary artery (RCA), including balloon angioplasty and stent placement. The procedure was completed successfully with an excellent final result. The report also includes a note advising long-term dual antiplatelet therapy and warning about the inherent risks of stents.

**Key observations:**
- PTCA performed on LCX and RCA with 2 stents deployed
- LCX: Stented with LAD-GRACE 3.0 X 16 mm at 12 atm; post-dilatation with Sapphire nc 3.25 x 12 mm balloon at 19 atm
- RCA: Stented with GRACE 2.75 X 32 mm at 11 atm; post-dilatation with Sapphire nc 3.0 x 10 mm balloon at 19 atm
- Patient advised to continue long-term dual antiplatelet therapy
- Note on inherent risks of stents: restenosis and thrombosis

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
LCX : Using 7F EBU 3.0 catheter,Left coronary ostium was engaged and 0.014 Fielder FC Wire was advanced in the distal LAD.The lesion was dilated with Sapphire 2.0 X 10 mm balloon at 16 atm,and stented with LAD- GRACE 3.0 X 16 mm at 12 atm,Post-dilatation done with Sapphire nc 3.25 x 12 mm balloon at 19atm.with an excellent final result. .

RCA : Using 6F JR 3.0 catheter ,Right coronary ostium was engaged and 0.014 Sion Blue wire was advanced in the distal RCA.The lesion was dilated with Sapphire 2.0 X 10 mm balloon at 16 atm, and stented with GRACE 2.75 X 32 mm at 11 atm. Post-dilatation done with Sapphire nc 3.0 x 10 mm balloon at 19 atm. with an excellent final result.

PTCA TO LCX & RCA WITH 2 STENT DONE.
LONG TERM DUAL ANTIPLATELETS.
Note: All stents having inherent risk of restenosis and thrombosis.Please continue antiplatelet drugs regularly. Do not stop medicines without consulting Physician or Cardiologist

सुचना * पुड़ील वेक्स येतांना हा कमाद सोबत आपणावा. * औषधाची अंतर्ल्यास प्रथम सांगणे. * औषधे डॉक्टरांना वाखूरूच घ्या.
Phone :
```

</details>

**English:**

```
LCX : Using 7F EBU 3.0 catheter,Left coronary ostium was engaged and 0.014 Fielder FC Wire was advanced in the distal LAD.The lesion was dilated with Sapphire 2.0 X 10 mm balloon at 16 atm,and stented with LAD- GRACE 3.0 X 16 mm at 12 atm,Post-dilatation done with Sapphire nc 3.25 x 12 mm balloon at 19atm.with an excellent final result. .

RCA : Using 6F JR 3.0 catheter ,Right coronary ostium was engaged and 0.014 Sion Blue wire was advanced in the distal RCA.The lesion was dilated with Sapphire 2.0 X 10 mm balloon at 16 atm, and stented with GRACE 2.75 X 32 mm at 11 atm. Post-dilatation done with Sapphire nc 3.0 x 10 mm balloon at 19 atm. with an excellent final result.

PTCA TO LCX & RCA WITH 2 STENT DONE.
LONG TERM DUAL ANTIPLATELETS.
Note: All stents having inherent risk of restenosis and thrombosis.Please continue antiplatelet drugs regularly. Do not stop medicines without consulting Physician or Cardiologist

Note: All stents have inherent risk of restenosis and thrombosis. Please continue antiplatelet drugs regularly. Do not stop medicines without consulting Physician or Cardiologist

Information: * Please take this medicine with food. * Inform the doctor before taking any medicine. * Take medicines as advised by the doctor.
Phone :
```

---

## [15] 000256__PMJAY_MH_S_G_R1_2026032910015645__PTCA_REPORT.pdf — page 3/3

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Stents visible in RCA and LCX branches)  ·  **Quality:** good

**Summary.** A coronary angiography diagram showing stents deployed in the left circumflex (LCX) and right coronary artery (RCA) branches. Two stents are visible, with labels indicating their manufacturer (SMT Cardiovascular), model (Supralimus Grace), and specifications. Handwritten notes indicate 'PTCA to LCX & RCA with 2 stent done' and 'Long Term Dual Antiplatelet' as advice.

**Key observations:**
- Stents are visible in the RCA and LCX coronary arteries.
- Two stents are present: one 3.00 mm x 16 mm and one 2.75 mm x 32 mm.
- Handwritten impression states 'PTCA to LCX & RCA with 2 stent done'.
- Handwritten advice states 'Long Term Dual Antiplatelet'.

**Dates found:** 31/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
CORONARY ANGIOGRAPHY DIAGRAM
Patient Name: 
Date: 31/03/2026
Doctor Name: 
Age: 73 □M □F
Cath No: 2414/03/2026
Indoor No: AHM-

LM
CX
OM
DIAG
RCA
LAD
PD

SMT Cardiovascular
Private Limited
SUPRALIMUS GRACE
3.00 mm x 16 mm
REF: FGTG300016
SN: (21)T25TGAES300016001
LOT: (10)T25TGAEEAAA
E: (17)2027-09

SMT Cardiovascular
Private Limited
SUPRALIMUS GRACE
2.75 mm x 32 mm
REF: FGTG275032
SN: (21)T26TGAAS275032117
LOT: (10)T26TGAIAA
E: (17)2028-01

IMP: PTC A TO LCX & RCA WITH 2 STENT DONE
ADV: Long Term Dual Antiplatelet
```

</details>

---

## [16] 000264__PMJAY_MH_S_G_R1_2026032910015645__CAG_REPORT.pdf — page 1/2

**Type:** Typed report  ·  **Body region:** Coronary tree  ·  **Stage:** post-procedure (Report includes impression and recommendation for intervention (PTCA))  ·  **Quality:** good

**Summary.** This is a typed Coronary Angiography Report for a 73-year-old female patient. The report details findings of stenosis in the left circumflex and right coronary arteries, with an impression of 'DVD' (Disease of the Vessels) and a recommendation for PTCA (Percutaneous Transluminal Coronary Angioplasty) on the LCX and RCA.

**Key observations:**
- Patient is 73 years old, female.
- Left Main and LAD arteries are described as normal.
- Left Circumflex artery shows 95% stenosis at the ostium with a mid-plaque.
- Right Coronary Artery shows 80% stenosis at the ostium.
- Recommendation is PTCA for LCX and RCA.
- Report includes a notice in Hindi regarding document and allergy information.

**Dates found:** 28/03/2026, 2404/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
NAME : 
AGE : 73YRS
CATH ID : 2404/03/2026
DATE : 28/03/2026
SEX : FEMALE
IP NO : AHH-1798/03/26

CORONARY ANGIOGRAPHY REPORT

ROUTE : RT-Radial
LEFT MAIN : Normal
LEFT ANTERIOR DESCENDING : LAD Type, II Shows, Normal
Diagonal Branch Shows, Normal
LEFT CIRCUMFLEX : LCX Non- Dominant shows Mliid Plaque Ostial & 95% Stenosis
In Proximal LCX.
QM Branch shows Normal.
RIGHT CORONARY ARTERY : RCA Dominant shows 80% Stenosis In Ostial RCA.
PDA Branches shows Normal. PLV Branch shows Normal.

IMPRESSION : DVD.
RECOMMENDATION : PTCA TO LCX & RCA .

सुचना * पुडील वेक्स येताना हा कागद सोबत आणावा. * ओळखाची अॅलर्जी असल्यास प्रथम सांगणे. * ओळखे अॅक्टरांना दाखवून घ्या.
Phone : (
```

</details>

**English:**

```
NAME :
AGE : 73YRS
CATH ID : 2404/03/2026
DATE : 28/03/2026
SEX : FEMALE
IP NO : AHH-1798/03/26

CORONARY ANGIOGRAPHY REPORT

ROUTE : RT-Radial
LEFT MAIN : Normal
LEFT ANTERIOR DESCENDING : LAD Type, II Shows, Normal
Diagonal Branch Shows, Normal
LEFT CIRCUMFLEX : LCX Non- Dominant shows Mliid Plaque Ostial & 95% Stenosis
In Proximal LCX.
QM Branch shows Normal.
RIGHT CORONARY ARTERY : RCA Dominant shows 80% Stenosis In Ostial RCA.
PDA Branches shows Normal. PLV Branch shows Normal.

IMPRESSION : DVD.
RECOMMENDATION : PTCA TO LCX & RCA .

Notice * Please bring this document with you. * If you have an allergy, inform first. * Show identification to the staff.
Phone : (
```

---

## [17] 000264__PMJAY_MH_S_G_R1_2026032910015645__CAG_REPORT.pdf — page 2/2

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Handwritten intervention plan (PTCA) visible)  ·  **Quality:** good

**Summary.** A hand-drawn coronary angiography diagram showing the coronary tree with annotations indicating stenosis in the RCA (80%) and CX (95%), a nodular lesion (NOD), and a planned intervention (PTCA) to the LCX and RCA.

**Key observations:**
- Coronary tree diagram with labeled vessels: LM, DIAG, CX, OM, LAD, PD, RCA
- Annotations indicate 80% stenosis in RCA and 95% stenosis in CX
- Handwritten note: 'NOD' (likely nodular lesion) near CX
- Intervention plan: 'PTCA TO LCX 4 RCA' (Percutaneous Transluminal Coronary Angioplasty to Left Circumflex and Right Coronary Artery)
- Patient age: 73, female (□M □F)
- Date: 28/3/2026

**Dates found:** 28/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
CORONARY ANGIOGRAPHY DIAGRAM
Patient Name
Doctor Name
Cath No. : 2404/3/2026
Date: 28/3/2026
Age: 73 □M □F
Indoor No. : AHM-1798/3/2026
LM
DIAG
CX
OM
LAD
PD
RCA
80%.
95%.
NOD
IMP: DVO
ADV: PTCA TO LCX 4 RCA
```

</details>

---

## [18] 000274__PMJAY_MH_S_G_R1_2026032910015645__CAG_IMAGES.pdf — page 1/3

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 7° / CRAN 36°  ·  **Stage:** intra-procedure (Cath-lab monitor UI visible with 'AXIOM-Artis' and 'RAO/LAO/CRAN/CAUD N°' overlays; coronary artery tree visualized with contrast opacification)  ·  **Quality:** good — Image is a photograph of a monitor screen, not a direct radiographic capture, Partial redaction of patient identifiers and other fields, UI overlays may obscure anatomical details

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system in a 73-year-old female patient. The image is acquired in a RAO 7° / CRAN 36° projection, with overlay UI elements indicating the equipment (AXIOM-Artis), acquisition parameters, and image processing settings.

**Key observations:**
- Coronary artery tree visualized with contrast opacification
- Patient identifier: 73/F
- Acquisition date: 3/28/2026
- Projection: RAO 7° / CRAN 36°
- Image processing settings: EE 26%, DDO 50%, WC 2050, WW 2300
- Equipment: AXIOM-Artis VD12A 24-1011

**Dates found:** 03/28/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24/04/03/2026
* 3/28/2026
6:29:46 PM
8 - 30/61
1.90 sec
73/F
AXIOM-Artis
VD12A 24-1011
HFS
/com//E//
CARD 15 f/s
STO
View Image DSA
Adjust Calib. Tools
2050
2300
EE 26%
DDO 50%
WC 2050
WW 2300
Coro 2020
cm 20
A
D 168
RAO 7° / CRAN 36°
```

</details>

---

## [19] 000274__PMJAY_MH_S_G_R1_2026032910015645__CAG_IMAGES.pdf — page 2/3

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 37° / CAUD 29°  ·  **Stage:** intra-procedure (Catheter and contrast medium visualized in coronary arteries)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with catheter and contrast medium. The view is LAO 37° / CAUD 29°, acquired on 3/28/2026 at 6:30:05 PM. Patient is 73-year-old female. Image parameters include EE 27%, DDO 50%, WC 2050, WW 2300.

**Key observations:**
- Coronary artery tree visualized with contrast medium
- Left anterior oblique (LAO) 37° and caudal 29° projection
- Patient age 73, female
- Acquisition date: 3/28/2026, time: 6:30:05 PM
- Image parameters: EE 27%, DDO 50%, WC 2050, WW 2300
- Equipment: AXIOM-Artis VD12A

**Dates found:** 03/28/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24/04/03/2026 73/F * 3/28/1953 3/28/2026 6:30:05 PM 9 - 32/58 2.03 sec AXIOM-Artis VD12A 24:10:11 HFS /com//El/ Coro 2020 cm 20 A D 167 LAO 37° / CAUD 29° EE 27% DDO 50% WC 2050 WW 2300
```

</details>

---

## [20] 000274__PMJAY_MH_S_G_R1_2026032910015645__CAG_IMAGES.pdf — page 3/3

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 35° / CAUD 1°  ·  **Stage:** intra-procedure (Coronary angiogram image with catheter tip visible in left coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with a catheter tip visible. The image is displayed on a Siemens Artis workstation with acquisition parameters and patient details overlaid.

**Key observations:**
- Left coronary artery system visualized
- Catheter tip visible within the vessel
- Image acquired at 6:20 PM on 3/28/2026
- View angle: LAO 35° / CAUD 1°
- Patient age: 73 years, female
- Image parameters: EE 28%, DDO 50%, WC 2050, WW 2300

**Dates found:** 03/28/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2404/03/2026
73/F
* 3/28/2026
6:20:00 PM
1 - 17740
1.04 sec
AXIOM-Artis
VD12A 241011
HFS
/com///E//
CARD 15 f/s
STOP
View Image DSA
Adjust Tools
EE 28%
DDO 50%
WC 2050
WW 2300
Coro 2020
cm 20
A
D 168
LAO 35° / CAUD 1°
```

</details>

---
