# Image Catalog — PMJAY_MH_S_G_R1_2026032610038286_P

**Package:** MC011A  ·  **Model:** accounts/ajeya-rao-k-eckusf6m/deployments/euufjyfd  ·  **Images:** 16

## Overview

| # | Source | Page | Type | Body region | Stage | Quality |
|---|--------|------|------|-------------|-------|---------|
| 0 | 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf | 1/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 1 | 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf | 2/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 2 | 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf | 3/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 3 | 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf | 4/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 4 | 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf | 5/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 5 | 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf | 6/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | ? |
| 6 | 000287__PMJAY_MH_S_G_R1_2026032610038286__PTCA_STENT.pdf | 1/2 | Typed report | Coronary tree — left system | post-procedure | good |
| 7 | 000287__PMJAY_MH_S_G_R1_2026032610038286__PTCA_STENT.pdf | 2/2 | Coronary Angiogram | Coronary tree — left system | post-procedure | good |
| 8 | 000295__PMJAY_MH_S_G_R1_2026032610038286__CAG.pdf | 1/2 | Typed report | Coronary tree — left system | post-procedure | good |
| 9 | 000295__PMJAY_MH_S_G_R1_2026032610038286__CAG.pdf | 2/2 | Coronary Angiogram | Coronary tree — left system | post-procedure | good |
| 10 | 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf | 1/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 11 | 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf | 2/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 12 | 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf | 3/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 13 | 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf | 4/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 14 | 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf | 5/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 15 | 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf | 6/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |

## [0] 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf — page 1/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 25° / CAUD 31°  ·  **Stage:** intra-procedure (Catheter and contrast medium visible in coronary arteries)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with contrast medium. The image is captured from a RAO 25° / CAUD 31° projection during an interventional procedure.

**Key observations:**
- Coronary arteries visualized with contrast medium
- Patient identifier: 81/F
- Procedure date: 24/01/03/2026 (likely 24th March 2026)
- Image acquisition parameters: RAO 25° / CAUD 31°, EE 26%, DDO 50%, WC 1933, WW 2300
- Equipment: AXIOM-Artis system

**Dates found:** 24/01/03/2026, 3/27/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24/01/03/2026 81/F H 3/27/2026 5:31:47 PM 1-13/19 0.75 sec AXIOM-Artis VD12A 241011 HFS /com//// CARD 15 f/s STOP View Image DSA Adjust Calib Tools PostProc Quant Finishing Coro 2020 cm 20 A D 186 RAO 25° / CAUD 31° EE 26% DDO 50% WC 1933 WW 2300
```

</details>

---

## [1] 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf — page 2/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 25° / CAUD 31°  ·  **Stage:** intra-procedure (Guidewire visible within coronary vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within a coronary vessel, captured during an interventional procedure. The image displays patient and machine parameters on a monitor interface.

**Key observations:**
- A guidewire is visible traversing a coronary vessel.
- Image is captured on a cath-lab monitor with UI overlays.
- Patient identifier '81/F' and date '3/27/2026' are visible.
- View angle is RAO 25° / CAUD 31°.
- Machine model 'AXIOM-ARTIS' and acquisition parameters are displayed.

**Dates found:** 27/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
24917U5/2026
* 3/27/1945
3/27/2026
5:37:33 PM
3 - 41/54
2.62 sec
Coro 2020
cm 20
A
D 172
RAO 25° / CAUD 31°
AXIOM-ARTIS
VD12A 241011
HFS
/com////
EE 27%
DDO 60%
WC 1881
WW 2300
```

</details>

---

## [2] 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf — page 3/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 25° / CAUD 31°  ·  **Stage:** intra-procedure (Guidewire visible in coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a PTCA procedure showing the left coronary artery with a guidewire in place. The image is captured at an oblique angle (RAO 25° / CAUD 31°) and displays cath-lab interface controls and patient data.

**Key observations:**
- Guidewire visible within the coronary artery
- Patient identifier: 81/F
- Procedure: PTCA
- Date: 3/27/2026
- Image acquisition time: 5:48:13 PM
- View angle: RAO 25° / CAUD 31°
- Cath-lab system: AXIOM-Artis
- Image parameters: EE 28%, DDO 60%, WC 1870, WW 2300

**Dates found:** 03/27/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
PTCA
2401/09/2025
* 3/27/1945
3/27/2026
5:48:13 PM
11 - 22/27
1.36 sec
R
Coro 2020
cm 20
A
D 172
RAO 25° / CAUD 31°
AXIOM-Artis
VD12A 241011
HFS
/com////
CARD 15 f/s
STOP
EE 28%
DDO 60%
WC 1870
WW 2300
```

</details>

---

## [3] 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf — page 4/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 25° / CAUD 31°  ·  **Stage:** intra-procedure (Guidewire and catheter visible within coronary vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a PTCA (Percutaneous Transluminal Coronary Angioplasty) procedure showing a guidewire and catheter within the coronary artery. The view is angled RAO 25° / CAUD 31°, and the image is from a Siemens AXIOM-Artis system.

**Key observations:**
- Guidewire and catheter are visible within the coronary vessel.
- Image is captured during an intra-procedure PTCA.
- View is RAO 25° / CAUD 31°, indicating a specific angulation for visualization.
- Image metadata includes patient ID, date, time, and system settings (EE 27%, DDO 50%, WC 1850, WW 2300).

**Dates found:** 09/2026, 3/27/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
PTCA
2401/09/2026
* 3/27/2026
5:48:22 PM
12 - 134/151
8.81 sec
Coro 2020
cm 20
A
D 170
RAO 25° / CAUD 31°
AXIOM-Artis
VD12A 241011
HFS
/com////
CARD 15 f/s
STOP
EE 27%
DDO 50%
WC 1850
WW 2300
```

</details>

---

## [4] 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf — page 5/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 25° / CAUD 31°  ·  **Stage:** intra-procedure (Guidewire visible within coronary vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within a coronary artery, captured during an interventional procedure. The image displays cath-lab interface elements including acquisition parameters and view angles.

**Key observations:**
- Guidewire is visible within a coronary vessel
- Image acquired at 5:49:07 PM on 3/27/2026
- View angle is RAO 25° / CAUD 31°
- Image parameters: CARD 15 f/s, EE 28%, DDO 50%, WC 1837, WWW 2300
- System: AXIOM-ARTIS, VD12A 241011

**Dates found:** 03/27/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2401/03/2026
* 3/27/1945
3/27/2026
5:49:07 PM
20 - 52/85
3.36 sec
R
Coro 2020
cm 20
A
D 170
RAO 25° / CAUD 31°
AXIOM-ARTIS
VD12A 241011
HFS
/com////
CARD 15 f/s
STOP
EE 28%
DDO 50%
WC 1837
WWW 2300
```

</details>

---

## [5] 000286__PMJAY_MH_S_G_R1_2026032610038286__PTCA_IMAGES.pdf — page 6/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 25° / CAUD 31°  ·  **Stage:** intra-procedure (Coronary angiogram with contrast opacification of vessel lumen, catheter tip visible, no stent deployed)

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
PTCA
2401/03/2026
* 3/27/1945
3/27/2026
5:52:24 PM
30 - 24/48
1.51 sec
R
Coro 2020
cm 20
A
D 167
RAO 25° / CAUD 31°
AXIOM-Artis
VD12A 241011
HFS
/com////
CARD 15 f/s
STOP
EE 27%
DDO 50%
WC 1892
WW 2300
```

</details>

---

## [6] 000287__PMJAY_MH_S_G_R1_2026032610038286__PTCA_STENT.pdf — page 1/2

**Type:** Typed report  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Final result section describes 'Excellent final result' and 'Residual stenosis 0%')  ·  **Quality:** good

**Summary.** This is a typed report of a successful PTCA (Percutaneous Transluminal Coronary Angioplasty) procedure performed on the left circumflex artery (LCX) using a single drug-eluting stent. The procedure involved pre-dilatation, stenting, and post-dilatation, resulting in an excellent final outcome with no dissection, thrombus, or residual stenosis.

**Key observations:**
- Procedure: PTCA to LCX via right radial artery
- Stent used: LCX-GRACE 2.75 X 36 mm [DES]
- Final result: Excellent, TIMI-III flow, 0% residual stenosis
- Post-procedure instructions: Long-term dual antiplatelets required
- Note: Patient must continue antplatelet drugs and consult physician before stopping them

**Dates found:** 27/03/2024

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
NAME : DATE : 27/03/2024
AGE : 81 YRS ♀
CATH ID : 2401/03/2026
SEX : FEMALE
IP NO : AHH-1792/03/26
CORONARY ANGIOPLASTY REPORT - (PTCA)
Route : RIGHT RADIAL ARTERY
Procedure : PTCA TO LCX
Access : 7-F SHEATH
RFA : ,130/80 mmhg.
INJ Heparin : 10,000 IU
Guiding Catheter : 6F EBU 3.0
Coronary wire : Sion Blue
Pre-dilatation : Sapphire 2.5 X 12 mm. balloon at 12 atm.
Stent : LCX- GRACE 2.75 X 36 mm at 11 atm. [DES]
Post- dilatation : Sapphire nc 3.0 x 10 mm balloon at 18 atm.
Post Ptca Act : 290
Final result : Excellent final result, no haze / dissection / Thrombus TIMI-III Flow achieved
Residual stenosis 0%
LCX: Using 6F EBU 3.0 catheter, Left coronary Ostium was engaged and 0.014 Sion Blue ns wire was advanced in the distal LCX. The lesion was dilated with Sapphire 2.5 X 12 mm.balloon at 12 atm, and stented with LCX- GRACE 2.75 X 36 mm at 11 atm, Post-dilatation done with Sapphire nc 3.0 x 10 mm balloon at 18 atm. with an excellent final result.
PTCA TO LCX WITH SINGLE STENT DONE SUCCESSFULLY
LONG TERM DUAL ANTIPLATELETS.
Note: All stents having inherent risk of Re-stenosis and thrombosis. Please Continue ant platelet drugs regularly. Do not stop medicines without Consulting Physician or Cardiologist.
MD (MBBS), DM (Cardiology)
Interventional Cardiologist
सुचना * पुडील बेलेस येताना हा कागद सोबत आणावा. * औषधींची अंतर्ज्ञान अस्त्यास प्रथम सांगणे. * औषधे डॉक्टरांना दाखवूनच घ्या.
Phone :
```

</details>

**English:**

```
NAME : DATE : 27/03/2024
AGE : 81 YRS ♀
CATH ID : 2401/03/2026
SEX : FEMALE
IP NO : AHH-1792/03/26
CORONARY ANGIOPLASTY REPORT - (PTCA)
Route : RIGHT RADIAL ARTERY
Procedure : PTCA TO LCX
Access : 7-F SHEATH
RFA : ,130/80 mmhg.
INJ Heparin : 10,000 IU
Guiding Catheter : 6F EBU 3.0
Coronary wire : Sion Blue
Pre-dilatation : Sapphire 2.5 X 12 mm. balloon at 12 atm.
Stent : LCX- GRACE 2.75 X 36 mm at 11 atm. [DES]
Post- dilatation : Sapphire nc 3.0 x 10 mm balloon at 18 atm.
Post Ptca Act : 290
Final result : Excellent final result, no haze / dissection / Thrombus TIMI-III Flow achieved
Residual stenosis 0%
LCX: Using 6F EBU 3.0 catheter, Left coronary Ostium was engaged and 0.014 Sion Blue ns wire was advanced in the distal LCX. The lesion was dilated with Sapphire 2.5 X 12 mm.balloon at 12 atm, and stented with LCX- GRACE 2.75 X 36 mm at 11 atm, Post-dilatation done with Sapphire nc 3.0 x 10 mm balloon at 18 atm. with an excellent final result.
PTCA TO LCX WITH SINGLE STENT DONE SUCCESSFULLY
LONG TERM DUAL ANTIPLATELETS.
Note: All stents having inherent risk of Re-stenosis and thrombosis. Please Continue ant platelet drugs regularly. Do not stop medicines without Consulting Physician or Cardiologist.
MD (MBBS), DM (Cardiology)
Interventional Cardiologist
Note: * This document must be submitted with the patient. * Inform the doctor before taking any medicine. * Always show medicines to the doctor.
Phone :
```

---

## [7] 000287__PMJAY_MH_S_G_R1_2026032610038286__PTCA_STENT.pdf — page 2/2

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Stent deployed in LAD, handwritten note 'PTCA To LAD - Single Stent Done')  ·  **Quality:** good

**Summary.** A post-procedure coronary angiography diagram showing a deployed stent in the left anterior descending artery (LAD) after percutaneous transluminal coronary angioplasty (PTCA). The diagram includes patient and procedural details, stent specifications, and physician notes.

**Key observations:**
- Stent deployed in the LAD (left anterior descending artery)
- Handwritten note: 'PTCA To LAD - Single Stent Done'
- Stent manufacturer: Sahajanand Medical Technologies Limited, model: SUPRALIMUS GRACE, size: 2.75 mm x 36 mm
- Patient age: 81, procedure date: 27/03/2026
- Advised: Long term dual antiplatelets

**Dates found:** 27/03/2026, 17/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
CORONARY ANGIOGRAPHY DIAGRAM
Patient Name: Mrs. 
Doctor Name: Dr. Tushar A. Patil
Cath No.: 2401/03/26
Date: 27/03/2026
Age: 81
Indoor No.: AHH-174/03/26

Sahajanand Medical Technologies Limited
SUPRALIMUS GRACE
2.75 mm x 36 mm
REF: FGTG275036
SN: (21)S25TGANES275036010
LOT: (10)S25TGANEAE
B: (17)2027-05

IMP: PTCA To LAD - Single Stent Done
ADV: LONG TERM DUAL ANTIPLATELETS

MD (medicine) DM (Cardiology)
Interventional Cardiologist
```

</details>

---

## [8] 000295__PMJAY_MH_S_G_R1_2026032610038286__CAG.pdf — page 1/2

**Type:** Typed report  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Report includes 'IMPRESSION: SVD' and 'RECOMMENDATION: PTCA TO LCX', indicating post-procedural findings and intervention plan.)  ·  **Quality:** good

**Summary.** This is a typed Coronary Angiography Report for an 81-year-old female patient, detailing stenosis findings in the left coronary arteries and recommending PTCA to the LCX. The procedure was performed via RT-Radial route on March 21, 2026.

**Key observations:**
- Patient is 81 years old, female, cath ID 2380/03/2026, procedure date 21/03/2026.
- Left Anterior Descending (LAD) shows 40% stenosis in mid segment and 30% stenosis in diagonal branch ostium.
- Left Circumflex (LCX) shows 80% stenosis in proximal to mid segment; OM branch is normal.
- Right Coronary Artery (RCA) is dominant and shows normal vessels including PDA and PLV branches.
- Final impression is SVD (Single Vessel Disease) and recommendation is PTCA to LCX.
- Report signed by an Interventional Cardiologist.

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
NAME : 
AGE : 81Y
CATH ID :2380 / 03/2026
DATE : 21/03/2026
SEX : FEMALE
IP NO : AHH-1781/03/26
CORONARY ANGIOGRAPHY REPORT
ROUTE : RT-Radial
LEFT MAIN : Normal.
LEFT ANTERIOR DESCENDING : LAD Type, III Vessel Show 40% Stenosis In Mid LAD
Diagonal Branch Show, 30% Stenosis In Ostial D-1
LEFT CIRCUMFLEX : LCX Non-Dominant Vessel Shows 80% Stenosis In Prox-Mid LCX
OM Branch show Normal.
RIGHT CORONARY ARTERY : RCA Dominant Vessel Shows Normal
PDA Branches shows Normal. PLV Branch shows Normal.
IMPRESSION : SVD
RECOMMENDATION : PTCA TO LCX
MD (MED), DM (CARDIOLOGY)
INTERVENTIONAL CARDIOLOGIST
सुचना * पुडील वेलेस ब्रेटाना हा कागद सोबत आणावा. * औषधी अॅलर्जी असल्यास प्रथम सांगणे. * औषधे डॉक्टरांना दाखूरच घ्या.
Phone :
```

</details>

**English:**

```
NAME :
AGE : 81Y
CATH ID :2380 / 03/2026
DATE : 21/03/2026
SEX : FEMALE
IP NO : AHH-1781/03/26
CORONARY ANGIOGRAPHY REPORT
ROUTE : RT-Radial
LEFT MAIN : Normal.
LEFT ANTERIOR DESCENDING : LAD Type, III Vessel Show 40% Stenosis In Mid LAD
Diagonal Branch Show, 30% Stenosis In Ostial D-1
LEFT CIRCUMFLEX : LCX Non-Dominant Vessel Shows 80% Stenosis In Prox-Mid LCX
OM Branch show Normal.
RIGHT CORONARY ARTERY : RCA Dominant Vessel Shows Normal
PDA Branches shows Normal. PLV Branch shows Normal.
IMPRESSION : SVD
RECOMMENDATION : PTCA TO LCX
MD (MED), DM (CARDIOLOGY)
INTERVENTIONAL CARDIOLOGIST
Note: * Please bring this card with the prescription. * Inform the doctor if you have any allergy. * Take medicines only as prescribed by the doctor.
Phone :
```

---

## [9] 000295__PMJAY_MH_S_G_R1_2026032610038286__CAG.pdf — page 2/2

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Handwritten annotations indicate 'PTCA to LCx' (percutaneous transluminal coronary angioplasty to left circumflex artery), suggesting intervention was performed.)  ·  **Quality:** good

**Summary.** A hand-drawn coronary angiography diagram showing the coronary tree with annotations of stenosis percentages and planned intervention. The patient is 81 years old, and the procedure was performed on March 21, 2026.

**Key observations:**
- Hand-drawn schematic of the coronary arteries with labeled branches (LM, CX, OM, LAD, RCA, PD).
- Annotations indicate 80% stenosis in the OM branch and 30% in the DIAG branch.
- Handwritten notes indicate 'IMP: CAG - SUD' and 'ADV: Mon: PTC A to LCx', suggesting a planned percutaneous transluminal coronary angioplasty to the left circumflex artery.
- Patient age is 81, and the procedure date is March 21, 2026.
- Signature block of an 'Interventional Cardiologist' is present.

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
CORONARY ANGIOGRAPHY DIAGRAM
Patient Name: 
Doctor Name: 
Cath No.: 2386/03/2026
Date: 21/03/2026
Age: 81 □ M □ F
Indoor No.: AHH 781/03/26

LM
CX
OM
LAD
RCA
PD

IMP: CAG - SUD
ADV: Mon: PTC A to LCx

MD (medicine) DM (Cardiology)
Interventional Cardiologist
```

</details>

---

## [10] 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf — page 1/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 24° / CRAN 33°  ·  **Stage:** intra-procedure (Contrast-filled coronary artery with guidewire visible)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with a guidewire in place, captured during an interventional procedure.

**Key observations:**
- Left coronary artery system visualized with contrast
- Guidewire visible within the vessel lumen
- Angiographic view parameters: LAO 24° / CRAN 33°
- Patient identifier: 81/F
- Procedure time: 3/21/2026, 6:14:21 PM
- Image acquisition time: 1.84 seconds

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2885/03/2026 81/F
3/21/2026
6:14:21 PM
6-29/52
1.84 sec
AXIOM-Artis
VD12A 241011
HFS
/con/118/
Coro 2020
cm 20
A
D 168
LAO 24° / CRAN 33°
EE 26%
DDO 50%
WO 2050
WW 2800
```

</details>

---

## [11] 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf — page 2/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 40° / CAUD 1°  ·  **Stage:** intra-procedure (Guidewire visible within coronary artery lumen)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with a guidewire in situ. The image is acquired in LAO 40° / CAUD 1° projection, with patient age 81 and gender female. Acquisition parameters and equipment details are visible on the screen overlay.

**Key observations:**
- A guidewire is visible within the coronary artery lumen.
- Image acquired in LAO 40° / CAUD 1° projection.
- Patient identifier: 81/F (age 81, female).
- Acquisition date: 3/21/2025, time: 6:14:11 PM.
- Equipment: AXIOM-Artis, with window level (WC) 2050 and width (WW) 2301.
- Image acquisition time: 1.37 seconds.

**Dates found:** 21/03/2025

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2385/03/2028
81/F
*
3/21/2025
6:14:11 PM
5 - 22/41
1.37 sec
Coro 2020
cm 20
A
D 188
LAO 40° / CAUD 1°
AXIOM-Artis
VD12A 241011
HFS
/com//E//
EE 27%
DDO 50%
WC 2050
WW 2301
```

</details>

---

## [12] 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf — page 3/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 40° / CAUD 28°  ·  **Stage:** intra-procedure (Guidewire and catheter visible within coronary artery)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with a guidewire and catheter in place. The image is captured from a left anterior oblique (LAO) 40° and caudal 28° projection. Patient data and machine settings are displayed on the screen.

**Key observations:**
- Left coronary artery system visualized
- Guidewire and catheter present within vessel
- Projection: LAO 40° / CAUD 28°
- Machine: AXIOM-Artis, acquisition time: 6:13:49 PM on 3/21/2026
- Patient identifier: 81/F
- Image parameters: EF 27%, DDO 51%, WC 2050, WW 2700

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2386/03/2026
* 3/21/1945
3/21/2026
6:13:49 PM
4 - 18/35
1.11 sec
R
AXIOM-Artis
VD12A 241011
HPS
/com//E//
CARD 15%
View Image
Adjust Calib.
EF 27%
DDO 51%
WC 2050
WW 2700
Coro 2020
cm 20
A
D 166
LAO 40° / CAUD 28°
```

</details>

---

## [13] 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf — page 4/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** LAO 28° / CRAN 38°  ·  **Stage:** intra-procedure (Coronary angiogram frame with catheter tip and contrast opacification of coronary arteries)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with contrast opacification. The view is LAO 28° / CRAN 38°, acquired during an intra-procedure phase. Patient data and machine settings are visible on the monitor interface.

**Key observations:**
- Coronary angiogram frame showing left coronary artery system with contrast opacification
- View angle: LAO 28° / CRAN 38°
- Patient identifier: 81/F
- Acquisition time: 3/21/2026 6:13:33 PM
- Machine: AXIOM-Artis, CARD 15 %, EE 27%, DDO 60%
- Image acquisition parameters: Coro 2020, cm 20, D 167

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2385/03/2026
* 3/21/1945
3/21/2026
6:13:33 PM
3-32/48
2.03 sec
Coro 2020
cm 20
A
D 167
LAO 28° / CRAN 38°
AXIOM-Artis
VD12A 24/1011
HFS
/com//IE/
CARD 15 %
EE 27%
DDO 60%
WC 2050
WW 2300
```

</details>

---

## [14] 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf — page 5/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 9° / CRAN 34°  ·  **Stage:** intra-procedure (Coronary angiogram frame with catheter and contrast opacification of coronary arteries)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with contrast opacification. The image is captured from a cranial oblique (RAO 9° / CRAN 34°) view during an interventional procedure.

**Key observations:**
- Coronary angiogram frame with visible contrast-filled coronary arteries
- Patient identifier: 81/F
- Procedure date: 3/21/2026
- Image acquisition time: 6:13:14 PM
- View angle: RAO 9° / CRAN 34°
- Image acquisition parameters: EE 26%, DDO 80%, WC 2050, WW 2300
- Equipment: AXIOM-Artis VD12A 241011

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2385/03/2026
* 3/21/1945
3/21/2026
6:13:14 PM
2 - 44/56
2.82 sec

AXIOM-Artis
VD12A 241011
HFS
/com/III/EI
CARD 15%

Coro 2020
cm 20
A
D 167
RAO 9° / CRAN 34°

EE 26%
DDO 80%
WC 2050
WW 2300
```

</details>

---

## [15] 000301__PMJAY_MH_S_G_R1_2026032610038286__CAG_IMAGES_compressed.pdf — page 6/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO 32° / CAUD 23°  ·  **Stage:** intra-procedure (Angiographic contrast opacifies coronary vessels; catheter/ guidewire not visible; no stent or balloon deployed)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing the left coronary artery system with contrast opacification. The view is RAO 32° / CAUD 23°, acquired on 3/21/2026 at 6:13:02 PM. No intervention devices are visible.

**Key observations:**
- Left coronary artery system visualized with contrast
- RAO 32° / CAUD 23° projection
- Acquisition date: 3/21/2026
- Image acquired during intra-procedure phase
- Contrast opacification of vessel lumen
- Image from AXIOM-Artis system

**Dates found:** 21/03/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
2385/03/2026
* 3/21/2026
6:13:02 PM
1 - 32/48
2.03 sec
Coro 2020
cm 20
A
D 168
RAO 32° / CAUD 23°
AXIOM-Artis
VD12A 241011
HFS
/com//E//
CARD 15 l/s
EE 27%
DDO 50%
WC 2050
WW 2300
```

</details>

---
