# Image Catalog — BOCW_GJ_R3_2026040310046613_ER

**Package:** MC011A  ·  **Model:** accounts/ajeya-rao-k-eckusf6m/deployments/euufjyfd  ·  **Images:** 24

## Overview

| # | Source | Page | Type | Body region | Stage | Quality |
|---|--------|------|------|-------------|-------|---------|
| 0 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 1/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 1 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 2/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 2 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 3/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | poor |
| 3 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 4/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 4 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 5/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 5 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 6/16 | Typed report | Coronary tree — left system | post-procedure | good |
| 6 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 7/16 | Stamp/Signature | N/A | n/a | good |
| 7 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 8/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | fair |
| 8 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 9/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 9 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 10/16 | Stamp/Signature | N/A | n/a | good |
| 10 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 11/16 | Typed report | Coronary arteries | post-procedure | good |
| 11 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 12/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 12 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 13/16 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 13 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 14/16 | Chest X-Ray | Chest (PA) | n/a | good |
| 14 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 15/16 | Stamp/Signature | N/A | n/a | good |
| 15 | 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf | 16/16 | Typed report | Chest | n/a | good |
| 16 | 000012__BOCW_GJ_R3_2026040310046613__4d079c0c-a8a0-417e-87aa-6f277f84fa5a.jpg | — | Typed report | Coronary tree — left system | post-procedure | good |
| 17 | 000032__BOCW_GJ_R3_2026040310046613__1b2c9239-9dfc-4dd3-9d47-7e4ba5e6e498.jpg | — | Typed report | Coronary tree | post-procedure | ? |
| 18 | 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf | 1/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 19 | 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf | 2/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | fair |
| 20 | 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf | 3/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 21 | 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf | 4/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 22 | 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf | 5/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |
| 23 | 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf | 6/6 | Coronary Angiogram | Coronary tree — left system | intra-procedure | good |

## [0] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 1/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (CINE frame (20/32) with visible catheter and contrast opacification of coronary arteries)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing a CINE frame (20/32) of a coronary angiogram. The image displays the left coronary artery system with contrast opacification, and patient information (M, 063Y) is visible in the top-left corner.

**Key observations:**
- Coronary angiogram image captured on a Samsung monitor
- Patient is male, 63 years old (M 063Y)
- CINE frame 20 of 32, indicating a dynamic sequence
- Contrast-filled coronary arteries visible
- UI elements include 'VI3CATH' and case ID 'UC003043'

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
VI3CATH
20/32
CINE
```

</details>

---

## [1] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 2/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (CINE mode active (24/34), cath-lab UI overlays present)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing a left coronary angiogram in CINE mode. The coronary arteries are visualized as grey vessel structures against a dark background, with UI overlays indicating patient ID, gender, age, and frame number.

**Key observations:**
- Left coronary artery system visualized
- CINE mode active (frame 24 of 34)
- Patient identifier: UC003043, Male, 63 years
- Image captured on a Samsung monitor
- UI overlay 'VI3CATH' visible

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
VI3CATH
24/34
CINE
```

</details>

---

## [2] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 3/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Dark background with grey vessel structures and on-screen UI overlays including 'DESKTOP-V40B1E7' and '4/3/2026 11:04:58')  ·  **Quality:** poor — Significant noise and graininess, Photograph of a monitor, Low contrast, Blur

**Summary.** A fluoroscopic image from a cath-lab monitor showing a dark background with a grey vessel structure, likely a coronary artery, with two dark circular markers along its path. UI overlays indicate the image is from an intra-procedure angiogram session.

**Key observations:**
- A cath-lab monitor screenshot with a dark background and grey vessel structures.
- Two dark circular markers are visible along the vessel path.
- UI overlays show patient identifier 'UG003043', gender 'M', age '063Y', timestamp '4/3/2026 11:04:58', and workstation name 'DESKTOP-V40B1E7'.
- Image quality is poor with significant noise and graininess.

**Dates found:** 03/04/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UG003043.
M
063Y
4/3/2026 11:04:58
DESKTOP-V40B1E7
```

</details>

---

## [3] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 4/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Cath-lab monitor UI present, patient identifier 'M 063Y', frame number '8/29' visible)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system. The image displays vessel structures with a guidewire visible. UI elements indicate patient ID, frame number, and cine mode.

**Key observations:**
- Image is a screenshot of a cath-lab monitor (Samsung brand visible)
- Patient identifier: 'M 063Y' (Male, 63 years)
- Frame number: 8/29 (8th frame of a 29-frame cine sequence)
- Modality: 'V13CATH' (indicative of catheter-based procedure)
- Guidewire visible within the vessel lumen
- Dark background with grey vessel structures typical of fluoroscopy

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
V13CATH
8/29
CINE
```

</details>

---

## [4] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 5/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Guidewire visible within vessel lumen)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a coronary angiogram showing a guidewire within the coronary vasculature. Patient is male, 63 years old. Image is frame 153 of 188 in the series.

**Key observations:**
- A guidewire is visible within a coronary vessel.
- Patient identifier: UC003043, Male, 63 years old.
- Image is from a fluoroscopy monitor (FLUORO).
- Frame number 153 of 188 in the sequence.

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
V13CATH
153/188
FLUORO
```

</details>

---

## [5] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 6/16

**Type:** Typed report  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Handwritten annotations indicate 'PCI (2 DES) to LAD done' and '2.5 x 28mm (DES) Xience Prime' stent placement)  ·  **Quality:** good

**Summary.** This is a handwritten coronary angiography report showing a schematic of the coronary arteries with annotations indicating a stent placement in the left anterior descending artery (LAD). The report includes patient demographics, catheterization details, and comments confirming a percutaneous coronary intervention (PCI) with two drug-eluting stents (DES) was performed.

**Key observations:**
- Hand-drawn schematic of coronary arteries with labeled vessels (Cx, LAD, AM, PD, DM)
- Annotations indicate '2.5 x 28mm (DES) Xience Prime' stent deployed in the LAD
- Comments section states 'PCI (2 DES) to LAD done'
- Patient age is 63, sex is male
- Date is written as 03/104/2026 (likely a typographical error for 03/10/2026)
- Report header indicates 'Report of Coronary Angiography'

**Dates found:** 03/104/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
Report of Coronary Angiography
M.D. (Medicine)
DNB (Cardiology)
Ex. Cardiologist: Sai Hospital, Ahmedabad
Ex. Physician: Lions Hospital, Palanpur
Name: 
Age: 63
Sex: Male
Done by Dr.
I.P. No. U.I.-2234
MRD No.
CATH No. VC-3043
Date: 03/104/2026

DIAG
DIAG
DM
Cx
LAD
AM
PD
2.5 X 28mm
(DES)
Xience Prime

RAO

D-Acs: NMT EMZ
CAT: SVP
Comments:
PCI (2 DES) to LAD done

Cardiologist
```

</details>

---

## [6] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 7/16

**Type:** Stamp/Signature  ·  **Body region:** N/A  ·  **Stage:** n/a (N/A)  ·  **Quality:** good

**Summary.** The image shows the packaging of an Abbott XIENCE PRIME™ Everolimus Eluting Coronary Stent System, including specifications, dimensions, lot number, and expiration date.

**Key observations:**
- Product is a coronary stent system for use in percutaneous coronary intervention.
- Stent specifications include size (2.5 mm x 28 mm x 143 mm) and post-dilatation limit (0.36 mm).
- Expiration date is 2023-13-06 (likely a typo, should be 2023-06-13).
- Lot number is 0121-441.
- Contains a flushing tool and 120 mg Everolimus coating at 100 µg/cm³.

**Dates found:** 2023-13-06, 2023-19-17

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
XIENCE PRIME™
Everolimus Eluting Coronary Stent System

ATM kPa
9 9.9 0.13 mm
10 1410 0.20 mm
11 1117 0.25 mm
12 1215 0.27 mm
13 1317 0.30 mm
14 1419 0.33 mm
15 1521 0.36 mm
16 1623 0.39 mm
17 1725 0.42 mm
18 1827 0.45 mm
19 1929 0.48 mm
20 2031 0.51 mm
21 2133 0.54 mm
22 2235 0.57 mm

POST DILATATION LIMIT 0.36 mm

2.5 mm
28 mm
143 mm

UDI
0510877948735481 177281205110 212141

3038-12-04
LOT 0121-441

2.6 mm
2.8 / 1.88 mm
5 3/16" / 0.38 mm
1.4P / 0.75 mm
140 cm

FLUSHING TOOL

120 mg Everolimus
100 µg/cm³

EU / MRT

2023-13-06

WPL2130660-12 (2023-19-17)
```

</details>

---

## [7] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 8/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Fluoroscopic image with catheter tip visible)  ·  **Quality:** fair — Image is a photograph of a monitor screen, Low resolution and grainy appearance, Partial view of the anatomy, UI overlays obscure parts of the image

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram. A catheter tip is visible within the coronary vasculature. Patient identifier 'M 063Y' and acquisition details 'V13CATH', '20/48', 'FLUORO' are displayed on screen.

**Key observations:**
- A fluoroscopic image of the coronary vasculature
- A catheter tip is visible within the vessel
- Patient identifier 'M 063Y' and acquisition details are displayed on screen
- Image is a screenshot of a monitor (Samsung) with UI overlays

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
V13CATH
20/48
FLUORO
```

</details>

---

## [8] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 9/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Guidewire visible in vessel lumen)  ·  **Quality:** good

**Summary.** Fluoroscopic image from a cath-lab monitor showing a guidewire within a coronary vessel during an angiographic procedure. Patient is male, 63 years old. The image is a single frame from a fluoroscopy sequence.

**Key observations:**
- A guidewire is visible within a coronary vessel lumen.
- Patient identifier: M 063Y (male, 63 years old).
- Image is a fluoroscopic frame from a cath-lab monitor (label: FLUORO).
- Image header includes case ID UC003043 and catheter type V13CATH.

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
V13CATH
60/00
FLUORO
```

</details>

---

## [9] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 10/16

**Type:** Stamp/Signature  ·  **Body region:** N/A  ·  **Stage:** n/a (N/A)  ·  **Quality:** good

**Summary.** A product box for the Abbott XIENCE PRIME™ Everolimus Eluting Coronary Stent System, showing specifications, lot number, expiration date, and manufacturer details.

**Key observations:**
- Product is a coronary stent system for medical use.
- Stent size options listed from 8 to 23 mm.
- Expiration date: 2024-05-13.
- Lot number: 4032141.
- Manufactured in India.
- Contains 100 µg of Everolimus.
- Packaging includes a diagram of the stent and flushing tool.
- Date code: 3027-03-12 (likely manufacturing date).

**Dates found:** 2024-05-13, 2023-10-17

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
Abbott
Abbott
XIENCE PRIME™
Everolimus Eluting Coronary Stent System
ATM kPa
8 971 2.45 mm
9 1013 2.50 mm
10 1013 2.55 mm
11 1211 2.70 mm
12 1211 2.75 mm
13 1419 2.80 mm
14 1419 2.85 mm
15 1619 2.90 mm
16 1619 2.95 mm
17 1822 3.00 mm
18 1822 3.05 mm
19 1822 3.10 mm
20 2027 3.20 mm
21 2128 3.30 mm
22 2228 3.40 mm
23 2328 3.50 mm
POST DILATATION LIMIT 1.55 mm
2.5 mm
23 mm
143 mm
UDI
3027-03-12
LOT 4032141
2.5 mm
2.5 F / 0.98 mm
0.38 mm
2.4 F / 0.75 mm
142 mm
FLUSHING TOOL
vascular stent abbot
1440-46-4
100 µg Everolimus
100 µg/ml
STERILE
MD 2797
2024-05-13
WPL213086G-11 (2023-10-17)
Abbott Medical
5500 Lantec Drive
Santa Clara, CA 95054 USA
TEL: (408) 227-0802
FAX: (408) 227-0804
Outside USA: TEL: +1 861-676-4600
Outside USA FAX: +1 861-676-2021
Product of India
Abbott Vascular International BVBA
Paris-LUX, Cuijkseweg 10
1831 Diepen, BELGIUM
TEL: +32 2 744 14 11
FAX: +32 2 714 14 12
Abbott Vascular Netherlands BV
Argonaut 1, 8421 PH
Heerlen
The Netherlands
TEL: +31-(0)46-9403700
* indicates a trademark of the Abbott group of companies
```

</details>

---

## [10] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 11/16

**Type:** Typed report  ·  **Body region:** Coronary arteries  ·  **Stage:** post-procedure (PTCA report with stent deployment details and TIMI flow assessment)  ·  **Quality:** good

**Summary.** This is a typed PTCA (Percutaneous Transluminal Coronary Angioplasty) report detailing a PCI procedure with two drug-eluting stents deployed in the OM1 artery. The report includes catheter and guide wire details, pre- and post-dilatation parameters, stent specifications, and a TIMI flow grade of 3. It also notes the risk of stent thrombosis and re-stenosis.

**Key observations:**
- Procedure: PCI with two XIENCE PRIME stents deployed in OM1
- Stent sizes: 2.5*23 mm and 2.5*28 mm
- TIMI flow grade: 3 (good end result)
- Procedure date: 03/04/2026
- Stent expiration dates: 2027-03-12 and 2026-12-05
- Patient age/sex: 63 Y / M

**Dates found:** 03/04/2026, 2027-03-12, 2026-12-05

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
PTCA REPORT
NAME : 
AGE / SEX : 63 Y / M
IPD NO : 2234
PROCEDURE PTCA : PCI (2 DES) TO OM 1
ROUTE - RIGHT RADIAL ROUTE
PTCA : PCI (2 DES) TO OM 1
GUIDE CATHETER : 6F 3.5 EBU
GUIDE WIRE : RUNTHROUGH
PRE - DILATATION : 2.5 *15 MM AT 15 ATM FOR 20 SEC
STENT : : 2.5 *23 MM XIENCE PRIME AT 12 ATM FOR 20 SEC (OVER LAPED)
 : 2.5 *28 MM XIENCE PRIME AT 12 ATM FOR 20 SEC
POST DILATATION : 3.0 * 15 MM PIPIT NC AT 15 ATM FOR 20 SEC .
GOOD END RESULT TIMI - 3 FLOW
There is 5%-6% chances of stent thrombosis / re-stenosis in first year and 1%-2% thereafter.

XIENCE PRIME™
2.5 mm x 23 mm
(01) 0 8717548 12347 4
(17) 270312 (10) 4032141 (01) 5060
EXP 2027-03-12
REF 1011707-23
LOT 4032141

XIENCE PRIME™
2.5 mm x 28 mm
(01) 0 8717548 12348 1
(17) 261205 (10) 3121441 (01) 5481
EXP 2026-12-05
REF 1011707-28
LOT 3121441

Monday to Saturday : 10-00 am to 6-00 pm
For Emergency Mo.
```

</details>

---

## [11] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 12/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Fluoroscopic image with cath-lab UI overlays and vessel structures)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing the left coronary artery tree with a guidewire or catheter in place. Patient is male, 63 years old. Image is frame 24 of 26 in a sequence.

**Key observations:**
- Fluoroscopic image of the coronary arteries
- Guidewire or catheter visible within the vessel
- Patient age: 63 years (M)
- Image number: 24/26
- Cath-lab UI elements visible (VI3CATH, FLUORO)

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
VI3CATH
24/26
FLUORO
```

</details>

---

## [12] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 13/16

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **View:** RAO / Caudal  ·  **Stage:** intra-procedure (Guidewire visible in vessel lumen)  ·  **Quality:** good

**Summary.** Fluoroscopic image from a cath-lab monitor showing a guidewire within the coronary vasculature, likely during an interventional procedure. Patient is male, 63 years old. Image is a RAO/Caudal view from a Siemens Axiom Artis system.

**Key observations:**
- A guidewire is visible within a coronary vessel.
- Patient identifier: UC003043, Male, 63 years old.
- Image is a fluoroscopic frame from a cath-lab monitor.
- View is RAO/Caudal (42/300 frame number).
- System: VI3CATH, FLUORO (Siemens Axiom Artis)

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003043
M
063Y
VI3CATH
42/300
FLUORO
```

</details>

---

## [13] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 14/16

**Type:** Chest X-Ray  ·  **Body region:** Chest (PA)  ·  **View:** PA  ·  **Stage:** n/a (No procedural devices or contrast media visible; diagnostic image)  ·  **Quality:** good — Image is a photograph of a physical X-ray film, not a direct digital scan, Partial view of background environment, Text at bottom is partially obscured by red pixelation

**Summary.** A frontal chest X-ray showing the thoracic cage, lungs, and heart silhouette. The image is held by a hand and displays patient demographic and date information at the bottom.

**Key observations:**
- Patient age and gender: 63 years, male (63Y/M)
- Date of image acquisition: 04-04-2026
- Image orientation marker 'R' visible in top left corner
- Image appears to be a standard posteroanterior (PA) view
- Partial view of background environment including a fire extinguisher

**Dates found:** 04/04/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
63Y/M 04-04-2026-11 000Y 4/4/2026
```

</details>

---

## [14] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 15/16

**Type:** Stamp/Signature  ·  **Body region:** N/A  ·  **Stage:** n/a (N/A)  ·  **Quality:** good

**Summary.** Two product labels for XIENCE PRIME™ coronary stents, showing specifications, barcodes, reference numbers, lot numbers, and expiration dates.

**Key observations:**
- Two identical stent labels for XIENCE PRIME™, one 2.5 mm x 23 mm and the other 2.5 mm x 28 mm.
- Expiration dates: 2027-03-12 and 2026-12-05.
- Lot numbers: 4032141 and 3121441.
- Reference numbers: 1011707-23 and 1011707-28.
- Both labels have an 'RX' symbol indicating prescription drug status.

**Dates found:** 2027-03-12, 2026-12-05, 2024-03-13, 2023-12-06

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
XIENCE PRIME™
2.5 mm x 23 mm
(01) 0 8717648 12347 4
(17) 270312 (10) 4032141 (91) 5060
2027-03-12
REF 1011707-23
LOT 4032141
RX
XIENCE PRIME™
2.5 mm x 28 mm
(01) 0 8717648 12348 1
(17) 261205 (10) 3121441 (91) 5481
2026-12-05
REF 1011707-28
LOT 3121441
RX
```

</details>

---

## [15] 000009__BOCW_GJ_R3_2026040310046613__7a877f13-90de-4c5d-b2c8-c47d9bb0e2dd_compressed.pdf — page 16/16

**Type:** Typed report  ·  **Body region:** Chest  ·  **View:** A/P  ·  **Stage:** n/a (Clinical report describing findings from a chest X-ray)  ·  **Quality:** good

**Summary.** This is a typed radiology report for an X-ray chest A/P view dated 04/04/2026. The report lists findings including no pneumothorax, prominent bronchovascular markings, no collapse or mass lesions, normal cardiac shadow, and no displaced fractures. It suggests clinical correlation and includes the radiologist's signature and credentials.

**Key observations:**
- Report is for an X-ray chest A/P view dated 04/04/2026.
- Findings include no pneumothorax, prominent bronchovascular markings, and no active Koch's lesion.
- Normal cardiac shadow, hila, domes, and costophrenic angles reported.
- Report suggests clinical correlation and includes radiologist's signature and credentials.
- Document contains redaction and disclaimer text.

**Dates found:** 04/04/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
PATIENT NAME: REF BY: MD DNB CARDIO DATE: 04/04/2026 X-RAY CHEST A/P VIEW • No pneumothorax. • Both lung fields show prominent bronchovascular markings. • No collapse, consolidation cavity or mass lesion seen. • No active Koch's lesion seen. • Cardiac shadow normal. • Both hila appear normal. • Both domes normal. • Both costophrenic angles clear. • Bony ribs under vision no displaced fracture SUGGEST: clinical correlation. Thanks for reference. M.D. RE -17187 M.D. Consultant Radiologist & Sonologist Ex. Asst. Professor, Civil Hosp. A'bad Subject to Polanpur Jurisdiction Only | Not Valid for any Medico Legal Purpose
```

</details>

---

## [16] 000012__BOCW_GJ_R3_2026040310046613__4d079c0c-a8a0-417e-87aa-6f277f84fa5a.jpg

**Type:** Typed report  ·  **Body region:** Coronary tree — left system  ·  **Stage:** post-procedure (Handwritten annotations on angiography diagram, including 'PCI (2DER) Lead > 0.04mm' and '95% lesion' annotations)  ·  **Quality:** good

**Summary.** A hand-drawn schematic of a coronary angiography report showing annotations of coronary artery lesions and a PCI procedure. The patient is a 63-year-old male. The report indicates a 99% lesion in the non-dominant artery, a 95% lesion in the OM branch, and a 95% lesion in the LAD. The PCI procedure was performed with a 2DER lead > 0.04mm.

**Key observations:**
- Hand-drawn schematic of coronary arteries with annotations of lesions (99% and 95%)
- Annotations indicate PCI procedure with '2DER' lead > 0.04mm
- Patient age: 63, male
- Date of procedure: 03/04/2026
- Report includes 'NSTEMI' and 'SVD (lesion length 5.5mm)' findings

**Dates found:** 03/04/2026

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
Report of Coronary Angiography
M.D. (Medicine)
DNB (Cardiology)
Ex. Cardiologist : Sal Hospital, Ahmedabad
Ex. Physician : Lions Hospital, Palanpur
Name
Age: 63
Sex: Male
Done by Dr.
I.P. No. UT-2234
MRD No.
CATH No. UC-3042
Date: 03/04/2026
Non dominant
99% lesion
plaque
plaque
OM
95% lesion
LAD
Cath No. UC-3042
RAO
Comments:
D= Acs: NSTEMI
CAG: SVD (lesion length 5.5mm)
PCI: PCT (2DER) Lead > 0.04mm
Cardiologist
```

</details>

---

## [17] 000032__BOCW_GJ_R3_2026040310046613__1b2c9239-9dfc-4dd3-9d47-7e4ba5e6e498.jpg

**Type:** Typed report  ·  **Body region:** Coronary tree  ·  **Stage:** post-procedure (ADV: PCI (2 DES) LCX to OM 1)

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
Dr. Niles H. Patel (Gami)
M.D. (Medicine)
DNB (Cardiology)
Ex. Cardiologist : Sal Hospital, Ahmedabad
Ex. Physician : Lions Hospital, Palanour
NAME:
IP NO: UI-2234
OPERATOR: DR.
DIAGNOSIS : ACS: NSTEMI
PROCEDURE : CAG
ROUTE : RIGHT FEMORAL ROUTE
HAEMODYNAMIC DATA : AO PRESSURE 120 / 80 MMHG
LMCA : NORMAL
LAD : PROXIMAL 50 % PLAQUE, MID NORMAL , DISTAL NORMAL
DIAG.1: NORMAL
DIAG 2: NORMAL
LCX: PROXIMAL PLAQUE , DISTAL NORMAL
OM 1: 95 % LESION (> 50 MM LESION LENGTH) L-PDA NORMAL
RCA : NON DOMINANT, PROXIMAL 99 % LESION , MID NORMAL ,
DISTAL NORMAL ,
CAG : SVD
ADV: PCI (2 DES ) LCX TO OM 1
Monday to Saturday : 10-00 am to 6-00 pm
```

</details>

---

## [18] 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf — page 1/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Cath-lab monitor UI with 'VI3CATH' and 'CINE' overlay; guidewire visible in vessel)  ·  **Quality:** good

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system with a guidewire in place. The patient is a 63-year-old male. This is frame 31 of 65 in a cine sequence.

**Key observations:**
- Coronary angiogram image displayed on a Samsung monitor
- Guidewire visible within the coronary vessel
- Patient identifier: Male, 63 years old
- Frame number: 31/65 (Cine sequence)
- Cath-lab UI elements visible (VI3CATH, CINE)

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003042
M
063Y
VI3CATH
31/65
CINE
```

</details>

---

## [19] 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf — page 2/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Catheter and guidewire visible within coronary arteries)  ·  **Quality:** fair — Image is a photograph of a monitor screen, not a direct radiograph, Partial view of the heart and vessels, Low contrast and grainy appearance

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system with a catheter and guidewire in place.

**Key observations:**
- Coronary arteries visualized with contrast
- Catheter and guidewire present within the vessel lumen
- Monitor UI elements visible: case ID, patient age (063Y), catheter type (VI3CATH), frame number (29/43), and cine mode
- Image is a photograph of a monitor screen

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003042
M
063Y
VI3CATH
29/43
CINE
```

</details>

---

## [20] 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf — page 3/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Cine frame (33/65) with catheter overlay (VI3CATH) and angiographic UI)  ·  **Quality:** good — Image is a photograph of a monitor screen, Partial redaction of patient identifier, Standard cath-lab UI overlays present

**Summary.** A fluoroscopic image from a cath-lab monitor showing a left coronary angiogram in cine mode (frame 33 of 65). A catheter (VI3CATH) is visible within the coronary vasculature. Patient identifier is partially redacted.

**Key observations:**
- Coronary angiogram image displayed on a monitor
- Cine sequence frame 33/65
- Catheter labeled VI3CATH visible in vessel
- Patient identifier UC003042 with age 63Y
- UI panel with standard angiography controls visible

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003042
M
063Y
VI3CATH
33/65
CINE
```

</details>

---

## [21] 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf — page 4/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Cine sequence indicator '33/65 CINE' visible)  ·  **Quality:** good — Image is a photograph of a monitor screen, Redaction bars obscure patient identifier and other data, Low resolution due to screen capture

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system. The image is part of a cine sequence (frame 33 of 65). Patient identifier and catheter type are visible on screen.

**Key observations:**
- Coronary artery tree visualized with contrast medium
- Left coronary system anatomy shown
- Cine sequence indicator '33/65 CINE' confirms intra-procedure capture
- Patient identifier 'M 063Y' and catheter type 'VI3CATH' displayed on screen

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003042
M
063Y
VI3CATH
33/65
CINE
```

</details>

---

## [22] 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf — page 5/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Fluoroscopic image with cath-lab UI overlays and vessel opacification)  ·  **Quality:** good — Photograph of a monitor screen, Partial redaction of patient identifiers, Low resolution due to photographing a screen

**Summary.** A fluoroscopic image from a cath-lab monitor showing a left coronary angiogram with vessel opacification. UI overlays indicate patient ID, age, catheter type, and cine frame number.

**Key observations:**
- Coronary artery tree visible with contrast opacification
- Patient age: 63 years (063Y)
- Catheter type: V13CATH
- Frame 24 of 40 in a cine sequence
- Monitor brand: SAMSUNG

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003042
M
063Y
V13CATH
24/40
CINE
SAMSUNG
```

</details>

---

## [23] 000034__BOCW_GJ_R3_2026040310046613__6a9b3b4f-b9f3-4acc-a421-2ca8e45b37c6_compressed.pdf — page 6/6

**Type:** Coronary Angiogram  ·  **Body region:** Coronary tree — left system  ·  **Stage:** intra-procedure (Cath-lab monitor UI with 'VI3CATH' and 'CINE' overlay; vessel structures with contrast opacification)  ·  **Quality:** good — Image is a photograph of a monitor screen, not a direct radiograph, Partial view of the screen with red bars obscuring some UI elements, Low contrast in vessel structures due to grayscale display

**Summary.** A fluoroscopic image from a cath-lab monitor showing a coronary angiogram of the left coronary system with contrast opacification. The UI overlay indicates patient gender (M), age (063Y), and frame number (26/41) in a cine sequence.

**Key observations:**
- Coronary angiogram showing left coronary artery tree with contrast-filled vessels
- Monitor UI overlay with patient identifier 'M 063Y' and sequence info '26/41 CINE'
- Image captured during an interventional procedure (intra-procedure stage)
- Device or guidewire not clearly visible within the vessel lumen

**OCR** _(language: English)_

<details><summary>Verbatim (original script)</summary>

```
UC003042
M
063Y
VI3CATH
26/41
CINE
```

</details>

---
